import { Alexandria } from "next/font/google";
import "./globals.css";
import type { Metadata } from "next";
import CallSupport from "@/components/CallSupport";
import Providers from "@/context/Providers";
import { Toaster } from "@/components/ui/sonner"

// Configure Alexandria font
const alexandria = Alexandria({
  subsets: ["latin", "arabic"],
  weight: ["400", "700"],
  variable: "--font-alexandria",
});
export const metadata: Metadata = {
  title: "Inifinty",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html dir="rtl" lang="ar">
      <body className={`${alexandria.variable} font-sans relative`}>
        <Providers>
          <Toaster />
          {children}
        </Providers>
        <CallSupport />
      </body>
    </html>
  );
}
